apiVersion: v1
kind: Service
metadata:
  name: nginx-base-service
  namespace: dev
  labels:
    app: nginx-base-service
spec:
  type: NodePort
  selector:
    app: nginx-base-deployment
  ports:
    - port: 80             # Port the service will use inside the cluster
      targetPort: 80       # Port where the NGINX container is listening
      nodePort: 30007      # Fixed NodePort you want to use (must be between 30000-32767)
