apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-base-deployment
  namespace: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-base-deployment
  template:
    metadata:
      labels:
        app: nginx-base-deployment
    spec:
      containers:
      - name: nginx-base
        image: nginx # Replace with your application's container image
        ports:
        - containerPort: 80   # The port your application listens on inside the container